### PR TITLE
[DAS-948] Add dockerfile

### PR DESCRIPTION
**Pull request by alana-alfeche**
Ran successfully locally!
Screen Shot 2022-07-18 at 12 36 45 AM

### CODE REVIEW

**Comment by justin-viome** [comment]
Looks good, but I think the image should use specific package versions of each of the R libraries as well as R itself. We can update them manually if we need to.  I've run into issues in the past where new versions break something even though they're supposed to be backwards compatible...

**Comment by alana-alfeche** [comment]
@justin-viome I see that `install.packages` does not allow specific version. I will check out `install_versions`.


https://stackoverflow.com/a/12679452

**Comment by justin-viome** [comment]
Sounds good.  Something like the following using the "remotes" package should work: 

remotes::install_version('arrow', version = '8.0.0', repos = 'http://cran.us.r-project.org')

**Comment by alana-alfeche** [comment]
@justin-viome -- Just pushed my code change using `install_version` and tested successfully locally. 
Screen Shot 2022-07-25 at 11 30 54 AM

**Comment by alana-alfeche** [comment]
Latest image pushed successfully.
Screen Shot 2022-07-26 at 10 16 43 AM

**Comment by justin-viome** [comment]
Looks good

**Pull request merged**
